neo.hello: hello im dev
spring:
  datasource:
    username: root
    password: Root@123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.129.134:3306/demo_01?useUnicode=true&characterEncoding=utf-8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:map/*Map.xml
  type-aliases-package: com.common.bean.City
feign:
  hystrix:
    enabled: true
turbine:
  appConfig: customer,product
  aggregator:
    clusterConfig: default
  clusterNameExpression: "'default'"
  instanceUrlSuffix: /hystrix.stream  #没有的话会出现异常
  combine-host-port: true
